title: Experiment and Create
description: > # this means to ignore newlines until "baseurl:"
  An entrepreneur is a 'Rebel' who experiments and creates. Hacking and seeking for change or new features. Continuously learning to apply state of the art tech and ideas. 
  Resistance to fix features.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rebelion.la" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: RebelionLabs #if your site has a twitter account, enter it here

# Author Settings
author: Rebelion Labs (RL|LR)
author-img: la-rebelion-logo.png # add your photo
about-author: An entrepreneur is a 'Rebel' who experiments and creates. Hacking and seeking for change or new features. Continuously learning to apply state of the art tech and ideas.
social-twitter: RebelionLabs
social-facebook: # add your Facebook handle
social-github: la-rebelion # add your Github handle
social-linkedin: adrianescutia
social-email: viva(AT)rebelion(DOT)la

# Disqus    
discus-identifier: la-rebelion # add your discus identifier

# Tracker
analytics: G-5QXB4Y9B0R # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
#  - jekyll-spaceship

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
